version: "3"
services:
  api:
    build: 
      context: ./
      dockerfile: Dockerfile-test
    depends_on:
    - mongo
    links:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - PORT=4000
  mongo:
    image: mongo
    ports:
    - "27017"
